# Generated by Django 5.0.7 on 2024-07-16 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_recipe_remove_savedrecipe_recipe_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrecipe",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="savedrecipe",
            name="user",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="SavedRecipe",
        ),
    ]
